
import {a_o_model} from "./a_o_model.module.js"
import { f_write_file } from "./f_write_file.module.js"
import { f_s_file_autogenerated_comment } from "./f_s_file_autogenerated_comment.module.js"


var f_create_csharp_database_context_class = function(
    s_name_database = 'database.db'
){
    var s_generated_by_line = f_s_file_autogenerated_comment(import.meta.url.split("/").pop());

    var s_indentation = '        ';
    var s_class_name = "O_database_context_class";
    var s_file_content = `
    //${s_generated_by_line}
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Collections.Generic;

    public class ${s_class_name} : DbContext
    {
`+
        // public DbSet<Blog> Blogs { get; set; }
`
${a_o_model.map(o=> `${s_indentation}public DbSet<${o.s_name}> a_${o.s_name.toLowerCase() } {get;set;}`).join("\n")}

        public string s_path_database { get; }

        public ${s_class_name}()
        {
            var s_folder = Environment.SpecialFolder.LocalApplicationData;
            var s_path = Environment.GetFolderPath(s_folder);
            s_path_database = System.IO.Path.Join(s_path, "${s_name_database}");
        }

        // The following configures EF to create a Sqlite database file in the
        // special "local" folder for your platform.
        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite($"Data Source={s_path_database}");
    }
    `

    var s_path_file = `./../../${s_class_name}.cs`;
    console.log(s_path_file)

    f_write_file(
        s_path_file, 
        s_file_content
    );
    
}

export {f_create_csharp_database_context_class}