import { f_create_javascript_class } from "./f_create_javascript_class.module.js";
import {a_o_model} from "./a_o_model.module.js"

import { f_s_file_autogenerated_comment } from "./f_s_file_autogenerated_comment.module.js"

import { f_write_file } from "./f_write_file.module.js"

import { Database } from 'https://deno.land/x/denodb/mod.ts';
import { o_database_connector } from "../gitignored/o_database_connector.module.js";

const o_db = new Database(o_database_connector);

var f_create_database_table = function(){



}

export {f_create_database_table}