import { f_create_database_table } from "./f_create_database_table.module.js";
import {a_o_model} from "./a_o_model.module.js"

import { f_s_file_autogenerated_comment } from "./f_s_file_autogenerated_comment.module.js"

import { f_write_file } from "./f_write_file.module.js"

var f_create_database_tables = function(){


    for(let o_model of a_o_model){
        f_create_database_table(o_model)
    }


}

export {f_create_database_tables}